server:
  port: 8081

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: git@github.com:marcohc79/repo-config-server.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}